### ISSUE TITLE
Change from DECODE-0.3 to 0.4 is disabling way to pass data to zenroom

### ISSUE THREAD

**Issue by chespinoza** [DECODEproject/zenroom#17]
Hello, 
Using zenroom version `DECODE-0.3` I can pass data to it to encrypt and decrypt data, i.e:
`echo '{"myval":1}' | ./zenroom -k device_keys.json encode.lua - > my_encrypt_data`

but in the version `DECODE-0.4` I can't use this feature as now STDIN is being treating as lua code then I can't use the `DATA` global variable in my lua scripts as before.

https://github.com/DECODEproject/zenroom/blob/e7d5d8c7648d3f4cef289410accde7e1aa52a4cc/src/zenroom.c#L274

```
> echo '{"val":1}' | ./zenroom-static encode.lua -
[*] Zenroom - crypto language restricted execution environment DECODE-0.3
 .  Copyright (C) 2017-2018 Dyne.org foundation
 .  reading KEYS from file
 .  loaded file: device_keys.json (143 bytes)
 .  reading DATA from stdin
 .  loaded file: test2.lua (370 bytes)
 .  using default configuration
 .  done loading all extensions
Mydata Gp3HC8aXXaXwhxm92BMswrejGniqMNcdhamuWEEuRkhV5GnXoLkjW5Yh8dD1dRDQ1k9AHe68Mhxmb1vpBCdXTchEQ1V1kjUTvb8fQT
 .  used memory: 123370 bytes
 .  executed operations: 0
[*] Zenroom operations completed.
```

```
> echo '{"val":1}' | ./zenroom-static encode.lua -
[*] Zenroom - crypto language restricted execution environment DECODE-0.4
 .  Copyright (C) 2017-2018 Dyne.org foundation
 .  reading CODE from stdin
 .  loaded file (10 bytes)
 .  using default configuration
 .  loading language extensions
 .  done loading all extensions
[!] lua error
[!] [string "{"val":1}..."]:1: unexpected symbol near '{'
[!] Error detected. Execution aborted.
```

Additionally to this I wanted to test this issue in my mac with the v0.3 but there is no available builds in Jenkins for Mac with this version, so I built my own artefacts checking out v0.3 tag, but the resulting executable was showing v0.2 version.

Thanks in advance.

**Comment by jaromil** [comment]
Ahoy, I'm about to release DECODE-0.5. The DATA global is now passed from a file from command-line using the `-a` flag. So is the KEYS global using the `-k` flag. This was changed for POSIX.1b compliancy since stdin is processing code when using the shebang `#!/usr/local/bin/zenroom -`.

**Comment by chespinoza** [comment]
Ok, I added in our fork a makefile target to get a dynamic lib to be usable from another langs, I think with that would be ok.

**Comment by jaromil** [comment]
ok! please send a PR when stable.
on the 0.6 roadmap I have the task of building shared libs (also .dll) and adding an output buffer and size to the zenroom_exec signature to allow catching output in-memory rather than from stdout. Any other need on the interoperability front please let me know so that we sort out all issues in the next release.
