### ISSUE TITLE
Scalable argument passing

### ISSUE THREAD

**Issue by mdevilliers** [DECODEproject/zenroom#3]
Playing with zenroom and its working out pretty well. 

I think the "-a" for arguments is working out pretty well for simple scripts but it isn't easy to integrate with more complicated use cases. 

My use case is as follows:

I have:
 - a lua file e.g. foo.lua
 - a json file of keys e.g. keys.json
 - a process emitting data 

What I would like to do is something like

```
echo "{'temp' : 22.3}" | ./zenroom -a ./keys.json ./foo.lua
```

I would like the following to happen
- zenroom loads foo.lua
- get the keys from via the json.decode( arguments) 
- somehow get the data from the echo

Maybe a solution could be multiple arguments e.g 

```
./zenroom -a ./keys.json -a $( echo "{'temp' : 22.3}" )  ./foo.lua
```

and make arguments an array of values e.g.

```lua
keys =  json.decode( arguements[0])
data =  json.decode( arguements[1])
```

Maybe it could be something else? 

I do think that there should be a scalable way of passing data into zenroom. 
Ideally I would like to use it as follows - 

```
./zenroom ./foo.lua ./keys.json $( echo "{'temp' : 22.3}" )
```
My main reason would be one of familiarity.

**Comment by jaromil** [comment]
this makes very much sense to me and also according to the analysis i'm making with fredd right now.
Gimme a few days.

**Comment by jaromil** [comment]
one note: the zenroom will not keep runing and reading from stdin, but take a chunk process it and exit. This to make it much simplier and less risky to handle buffers, plus both the syntactic and semantic parsers are geared to "brittle" as soon as there is an error. so the "streaming" part will be in charge of the caller, to make data chunks and call zenroom on each. The time of init and teardown is very short. Said that, the way to operate you suggest is a good improvement, there are three different levels of mutability, the higher being the data input and the lower being the code, keys are in the middle... so makes sense to separate them. I anyway think they should be all passed from arguments and stdin configured by the "-" value so his is configurable...

**Comment by mdevilliers** [comment]
I think leaving the chunking of the data to the calling process is fine.

The key is for zenroom to provide the minimum building blocks so that it's usage can be composed by the calling process. I don't think zenroom has to do anything revolutionary just follow prior art.

**Comment by jaromil** [comment]
BTW what language are you calling it from? Go? because I'm also planning swig bindings so I'll start from what you have... OTOH I'm not sure this is a good idea since runtime linking defeats the process separation approach.. thinking loud. Let me know how you intend to call it just for me to prioritise future ideas.

**Comment by mdevilliers** [comment]
Not through a binding. Just via a shell and read the json.

**Comment by jaromil** [comment]
done in PR #4 along with other improvements. Refreshing builds on the sdk jenkins tonight

**Comment by jaromil** [comment]
here we go: https://sdk.dyne.org:4443/job/zenroom-static-amd64/lastSuccessfulBuild/artifact/src/zenroom-static
`-k file.json` will declare its contents in global variable "KEYS"
as well adding a `-` on the commandline will read from stdin and declare contents in global var "DATA"
