### ISSUE TITLE
Running zenroom_exec.js failes with error: Module.print is not a function

### ISSUE THREAD

**Issue by sguldemond** [DECODEproject/zenroom#44]
Hi @jaromil,

Last Wednesday we met at the Decode office of the gemeente, so I was excited to start working with Zenroom.
I downloaded the Zenroom-0.8.0-javascript package and tried to run 'zenroom_exec.js' with,
`node zenroom_exec.js examples/hello.lua`

but got an error saying,
```
 .  loading lua initialisation
/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:1
(function (exports, require, module, __filename, __dirname) { var Module=typeof Module!=="undefined"?Module:{};if(!Module.expectedDataFileDownloads){Module.expectedDataFileDownloads=0;Module.finishedDataFileDownloads=0}Module.expectedDataFileDownloads++;((function(){var loadPackage=(function(metadata){function runWithFS(){var fileData0=[];fileData0.push.apply(fileData0,[45,45,32,105,110,105,116,32,115,99,114,105,112,116,32,101,109,98,101,100,100,101,100,32,97,116,32,99,111,109,112,105,108,101,32,116,105,109,101,46,32,32,101,120,101,99,117,116,101,100,32,105,110,10,45,45,32,122,101,110,95,108,111,97,100,95,101,120,116,101,110,115,105,111,110,115,40,76,41,32,117,115,117,97,108,108,121,32,97,102,116,101,114,32,122,101,110,95,105,110,105,116,40,41,10,10,74,83,79,78,32,32,32,61,32,114,101,113,117,105,114,101,40,39,106,115,111,110,39,41,10,83,67,72,69,77,65,32,61,32,114,101,113,117,105,114,101,40,39,115,99,104,101,109,97,39,41,10,82,78,71,32,32

TypeError: Module.print is not a function
    at Array.<anonymous> (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:1:1065157)
    at _emscripten_asm_const_ii (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:1:1065763)
    at Array.Qc (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:5:59039)
    at fh (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:7:34701)
    at Mj (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:6:53516)
    at hh (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:7:35275)
    at Array.rg (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:7:8220)
    at Object.pB [as dynCall_vii] (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:13:42791)
    at invoke_vii (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:1:1160577)
    at _g (/.../Zenroom-0.8.0-javascript/nodejs/zenroom.js:7:27894)
```

I did wanted to get it working so I changed a function call in 'nodejs/zenroom.js' from,
`(function($0){Module.print(UTF8ToString($0))})`

to,
`(function($0){console.log(UTF8ToString($0))})`

which after running `node zenroom_exec.js examples/hello.lua` again returned,
```
 .  loading lua initialisation
Hello World!
in hex: 48656c6c6f20576f726c6421
in base64: SGVsbG8gV29ybGQh
re-assign from hex, length 12
as string: Hello World!
in base64: SGVsbG8gV29ybGQh
re-assign from base64, length 12
as string: Hello World!
in hex: 48656c6c6f20576f726c6421
[*] Zenroom operations completed.
 .  Zenroom teardown.
```

Is there a fix so I can use the default zenroom.js?
Thanks :)

Running this on Mac OS 10.13.6 with Node v8.6.0

**Comment by puria** [comment]
Hi @sguldemond, well that is by design, to allow the user to control the output and the stout behaviour. You can see for instance an example on

https://github.com/DECODEproject/zenroom/blob/eeb36395a7cc2e167771696c7c863dad46d9b3c7/docs/demo/shell_minimal.html#L156

hence on node environments you need some boilerplate, more on the emscripten documentation directly here: https://kripken.github.io/emscripten-site/docs/api_reference/module.html 

So in your case should be enough to
```javascript
var Module = {
  'print': text => console.log(text)
};
```

**Comment by sguldemond** [comment]
Thanks @puria !

I added the following to 'zenroom_exec.js',
`zenroom_module.print = text => console.log(text)`
which gave me the output in my console.

Maybe it's an idea to add that to the source file of 'zenroom_exec.js' ?
That way anyone who wants to test it can just run it immediately like it says in the file:
```
// try this script from nodejs with a script as argument:
// nodejs zenroom_exec.js examples/hello.lua
```

**Comment by puria** [comment]
Thank you, please PR, @sguldemond
