### ISSUE TITLE
Catching errors from Python

### ISSUE THREAD

**Issue by smulube** [DECODEproject/zenroom#47]
Operating System: Linux (Ubuntu 18.04)
Python version: 3.6.6
Zenroom bindings: Built from commit: d2601b3ab430e14477400d039848ca767a3240dd

---

Hey again, I'm trying to figure out how I can detect  an error when invoking Zenroom via the Python binding. I'm calling Zenroom using the following code:

```python
import ctypes
_zenroom = ctypes.CDLL('./_zenroom.so')

script = b'print("hello world")'

stdout_buf = ctypes.create_string_buffer(b'\000', 1024)
stdout_len = ctypes.c_size_t(1024)
stderr_buf = ctypes.create_string_buffer(b'\000', 1024)
stderr_len = ctypes.c_size_t(1024)

_zenroom.zenroom_exec_tobuf(
    script,
    None,
    None,
    None,
    1,
    ctypes.byref(stdout_buf),
    stdout_len,
    ctypes.byref(stderr_buf),
    stderr_len,
)

print(stdout_buf.value)
```

So the above works fine if Zenroom is passed a valid script, however if I change things to pass in a script with some error, e.g.:

```python
# missing close quote
script = b'print("hello world)'
```

and try running the above script again, I get the following string printed to stdout or stderr:

```bash
python3: [string "print("hello world?)"]:1: unfinished string near <eof>: Unknown error 280084567
```

and the script seems to immediately exit, without allowing me to do anything, i.e. I never reach the line `print(stdout_buf.value)` shown above.

I tried the following things:

* wrapping the call to `zenroom_exec_tobuf` inside a `try`/`except` block, but there is no exception raised that I can catch
* capturing the return int from `zenroom_exec_tobuf`, but when an error happens the script seems to exit before this point

Am I being dense - is this expected behaviour? I think what I'd expect is either to have `zenroom_exec_tobuf` throw some exception that I can catch, or to have it return a non-zero exit code which I can detect, and perhaps then throw an error of my own containing the output from stderr.

**Comment by jaromil** [comment]
This is expected behavior: the meaningful error is 'unfinished string near <eof>' which is a syntax error raised by the Lua parser and occurring before execution. Zenroom is meant to 'brittle' at any error and return.

**Comment by smulube** [comment]
that is I'm v.happy for Zenroom to be brittle and fail fast if passed invalid input, but I'd love to be able to handle that from the wrapper which I'd argue should be able to proceed and try again with some different inputs

**Comment by puria** [comment]
Hey @smulube still without the interface? or resolved...

If you need I can make a package (maybe also put it on pypi) like I made for https://github.com/puria/zenroomjs to have a useful/usable interface.
You think will be useful, for you?

**Comment by smulube** [comment]
Hey @puria,

I already made an attempt at what you are describing which you can see
here:
https://github.com/DECODEproject/zenroom-py

This works fine for what it does, but still suffers from the problem I
described above in that if you feed a script or data or even keys that has
an error, then the python interpreter seems to just exit without giving any
chance to catch the error.

This was the issue I was hoping to get soon some assistance with as it
seems that is an issue in the generated .so bindings rather than something
we could fix in a wrapper.

**Comment by puria** [comment]
Yeah, point is in JS I've got an https://github.com/puria/zenroomjs#error where I can register a callback that's is called if something goes wrong (cause I'm a lucky guy, and clemency of jaromil) for the EMSCRIPTEN part ... that solves 99% cases of node users

keep you updated

**Comment by jaromil** [comment]
ACK! the callback! maybe we can set one for all languages from swig, I see here http://www.swig.org/Doc3.0/SWIGDocumentation.html#SWIG_nn30 and think we can just assume the simpliest way since the error callback is only called from zenroom and doesn't needs to be used as a function too.

**Comment by puria** [comment]
Okay @smulube  updates... when syntax error occurs, zenroom raises a SIGSEGV, I'm digging why. It is actually very strange from the code should just return `EXIT_FAILURE`, I'll continue stracing...

Far from being a solution, but by using the `ctypes.errcheck` [:memo: here](https://docs.python.org/3/library/ctypes.html#ctypes._FuncPtr.errcheck) and handling the signal by registering a handler [like here](https://stackoverflow.com/questions/25691406/segmentation-fault-catch) I was able to prevent the python interpreter to stop. Not so convenient but... you know...

**Comment by puria** [comment]
Hey @smulube Fixed for now, on the wrapper side by spawn a new process (great idea @jaromil ) look at https://github.com/DECODEproject/zenroom-py/commit/e401b75654a70c62777f8a1fe4c626ea4c30faee 

a new dependency is needed by the way (on zenroom-py wrapper) so please `pip install -e .` before ;)
