### ISSUE TITLE
broken javascript

### ISSUE THREAD

**Issue by jaromil** [DECODEproject/Zenroom#57]
Likely related to last PRs the `javascript-*` targets are broken and consequently the online demo

Need to fix urgently in particular the `javascript-demo` target (wasm based)

To reproduce use `make check-js` on `javascript-asmjs` or `javascript-wasm`

**Comment by jaromil** [comment]
The culprit is commit 8adc6bfd363ca92535d8121232b9375e2f5ab266 thanks @dappiu

**Comment by puria** [comment]
Fixed by https://github.com/DECODEproject/Zenroom/commit/2b884c6e7f4f2b007055dc3f34f130228c099b75
