### ISSUE TITLE
AGPL seems a little bizzare for embedding

### ISSUE THREAD

**Issue by Skrylar** [DECODEproject/Zenroom#79]
For a system that is meant to be embedded (especially one to replace cryptographic primitives) it seems a bizzare choice that makes it, well, much more difficult to embed.

Some kind of link exception would make sense, although it _looks like_ (with the reference to "enterprise support" on the page, and the existence of a CLA) this is supposed to be dual licensed. But it doesn't appear _obvious_ that is the case either.

**Comment by jaromil** [comment]
Our sustainability plan is indeed dual licensing to Apache/MIT on agreed terms and we are happy to facilitate OEM. Perhaps we should be more explicit about it? @Andrea-Tabbles

**Comment by Jamesits** [comment]
+1 for a less restrictive license. Not going to criticize any choice, but there are some facts I'd like to address:

1. Zenroom is not end-user-facing software, plus it is a language runtime, so it will likely be distributed along with some other code. AGPL makes it impossible to distribute Zenroom together with anything that links to a non-(A)GPL library (e.g. Microsoft proprietary GUI libraries, or some binary blobs that initialize my microcontroller hardware)
2. The official website advertises that Zenroom works with Apple software, but AGPL is incompatible with iTunes software distribution agreements

**Comment by Skrylar** [comment]
I don’t know that [the FSF] have or would enforce #1 in that way. That
interpretation would mean anyone running any kind of AGPL software on
Windows was also in violation because while it’s mostly servers, they are
still linking to Winsock.

Servers on Linux similarly link indirectly with the kernel and directly
with socket libs and those can never be AGPL either (upgrade clauses were
removed long ago.)

There are other pieces of software (Zrythm) using AGPL with GUI libraries
and they do not seem to be all that concerned. Of course it does mean that
ex. Microsoft could never distribute it themselves.

I do not personally believe the licensing is appropriate and will lead to
many hard passes, but it’s their grant funds and not mine.

**Comment by Jamesits** [comment]
AGPL do have exceptions for linking to "system libraries", but the definition of a "system library" is:

> The "System Libraries" of an executable work include anything, other than the work as a whole, that (a) is included in the normal form of packaging a Major Component, but which is not part of that Major Component, and (b) serves only to enable use of the work with that Major Component, or to implement a Standard Interface for which an implementation is available to the public in source code form. A "Major Component", in this context, means a major essential component (kernel, window system, and so on) of the specific operating system (if any) on which the executable work runs, or a compiler used to produce the work, or an object code interpreter used to run it.

Winsocks (the implementation) is part of the Windows OS and is packaged with every recent release of Windows, so I guess linking against Winsocks is not a violation of AGPL. Zrythm's GUI is implemented in GTK (LGPL licensed) so it [does not violate AGPL](https://opensource.stackexchange.com/a/5638) either. But any library that is (a) not distributed with your OS and (b) is not open sourced would cause issues.
