### ISSUE TITLE
Build documentation question

### ISSUE THREAD

**Issue by fdeantoni** [DECODEproject/Zenroom#93]
I checked the [Build Instructions](https://dev.zenroom.org/#/pages/how-to-build) and tried to build the shared libs using `make shared` but that target does not seem to exist. The Makefile has other targets that do seem to work (.e.g. `make osx`) but these are not described in the above documentation though. Is there somewhere else I should look to create the static and/or shared libraries?

**Comment by puria** [comment]
Thanks, for reporting, will look and update. @adam-burns any new target for the android side? I see see https://github.com/DECODEproject/Zenroom/blob/master/build/linux.mk#L32 are they valid?

**Comment by adam-burns** [comment]
@fdeantoni building for Linux platform, current make targets are:
linux - for Zenroom executable
linux-lib - for Zenroom shared lib libzenroom.so

**Comment by adam-burns** [comment]
@puria I have a [pull request](https://github.com/DECODEproject/Zenroom/pull/92) open for cleaning up the Android build script along with config.mk to work with current Android SDK, NDK and Studio.

make targets android-arm, android-x86, android-aarch64 are working with this pull request but require the environment variable NDK_HOME to be set to the Android NDK path, ie

`NDK_HOME=~/Android/Sdk/ndk-bundle/ make android-arm
`
The build script build/build_android builds all 3 android targets and places them in a directory tree as expected in an Android Studio structure:
```
$ tree target/
target/
└── android
    └── jniLibs
        ├── arm64-v8a
        │   └── libzenroom.so
        ├── armeabi-v7a
        │   └── libzenroom.so
        └── x86
            └── libzenroom.so

5 directories, 3 files
```

**Comment by fdeantoni** [comment]
Thanks for the pointers! Is there a reason there is no similar `osx-lib` target?

**Comment by puria** [comment]
Then @adam-burns maybe you want to update the documentation (https://github.com/DECODEproject/Zenroom/blob/master/docs/pages/how-to-build.md) in your PR to reflect the changes

**Comment by adam-burns** [comment]
Thanks for the documentation prompt. The documentation for building the Android libraries was updated. However, the existing documentation also refers to the file `src/Zenlook.java` that was deleted at ec713870164ea2f9d79b76491fb86a032d356967. It contains generic JNI Java binding, maybe this file should be restored (say under `bindings/java`) together with the Android build documentation updated to include the new path?

**Comment by puria** [comment]
Yes, I thing is a good idea, would you proceed with that and restore the Zenroom.java and update it? Because in the meantime the bindings also changed... the verbosity param is not valid anymore and is passed via config. :heart_eyes:
